{% set name = "django-dbbackup" %}
{% set version = "4.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/django-dbbackup-{{ version }}.tar.gz
  sha256: c411d38d0f8e60ab3254017278c14ebd75d4001b5634fc73be7fbe8a5260583b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - django >=2.2
    - pytz

test:
  imports:
    - dbbackup
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/jazzband/django-dbbackup
  summary: Management commands to help backup and restore a project database and media.
  license: BSD-3-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - rxm7706
