# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  name: django-dbbackup
  version: "5.2.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name | replace('-', '_') }}-${{ version }}.tar.gz
  sha256: 72b11dd31758abcf8f2d405fd2efbc49c9624bc17196f8c68542d3dc8d8d53c3

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
    - hatchling
  run:
    - python >=${{ python_min }},<4.0
    - django >=4.2
tests:
  - python:
      imports:
        - dbbackup
      python_version: ${{ python_min }}.*
      pip_check: true

about:
  summary: Management commands to help backup and restore a project database and media.
  license: BSD-3-Clause
  license_file: LICENSE.md
  homepage: https://github.com/jazzband/django-dbbackup

extra:
  recipe-maintainers:
    - rxm7706
